version: "2"

linters:
  enable:
    # Bug finders
    - bodyclose          # HTTP response body closure
    - durationcheck      # Duration multiplication bugs
    - embeddedstructfieldcheck # Embedded struct field access issues
    - errorlint          # Error wrapping issues
    - errchkjson         # JSON encoding error checks
    - fatcontext         # Context misuse in loops
    - nilerr             # Returns nil even when error set
    - noctx              # Missing context.Context usage
    - nosprintfhostport  # URL construction bugs

    # Security
    - gosec              # Security issues

    # Code quality
    - cyclop             # Cyclomatic complexity
    - dupl               # Duplicated code blocks
    - gochecknoglobals   # Disallow global variables
    - gochecknoinits     # Disallow init functions
    - godot              # Check comment ending with period
    - nestif             # Deeply nested if statements
    - nlreturn           # Newline before return
    - canonicalheader    # HTTP header canonicalization
    - dupword            # Duplicate words (typos)
    - exhaustive         # Exhaustive switch statements
    - funcorder          # Function declaration order
    - goconst            # Repeated strings that could be constants
    - gocritic           # Bugs, performance, style issues
    - intrange           # Use range over integers (Go 1.22+)
    - mirror             # bytes/strings usage patterns
    - misspell           # Typos
    - modernize          # Suggest modern Go idioms
    - perfsprint         # Faster alternatives to fmt.Sprintf
    - predeclared        # Shadowing predeclared identifiers
    - unconvert          # Unnecessary type conversions
    - unparam            # Unused function parameters
    - usestdlibvars      # Use stdlib constants
    - wastedassign       # Wasted assignments

    # Test quality
    - nolintlint         # Validate nolint directives
    - paralleltest       # Parallel test best practices
    - testifylint        # Testify usage
    - thelper            # Test helper best practices
    - usetesting         # Use testing package features

  settings:
    goconst:
      min-occurrences: 3
    paralleltest:
      ignore-missing-subtests: true
    gosec:
      excludes:
        - G115  # Integer overflow - checked at runtime
        - G304  # File path from variable - paths are from config
        - G301  # Directory permissions 0755 - standard for non-sensitive
        - G306  # File permissions 0644 - standard for non-sensitive
        - G401  # MD5 - required by API protocol
        - G404  # math/rand - ok for sensor data simulation
        - G501  # MD5 import - required by API protocol

  exclusions:
    rules:
      # Sensor data uses append to build new slices intentionally
      - path: internal/sensordata/
        linters:
          - gocritic
        text: appendAssign
      # Test files can have repeated strings
      - path: _test\.go
        linters:
          - goconst
      # Global variables - justified exclusions:
      # 1. Read-only lookup tables (RegionConfigs, screenSizes, androidVersionToSDK)
      - path: internal/api/auth\.go
        linters:
          - gochecknoglobals
        text: RegionConfigs
      - path: internal/sensordata/system_info\.go
        linters:
          - gochecknoglobals
        text: (screenSizes|androidVersionToSDK)

      # 2. CLI flags bound by Cobra framework (Version, ConfigFile, NoColor)
      - path: internal/cli/root\.go
        linters:
          - gochecknoglobals
        text: (Version|ConfigFile|NoColor)

      # 3. Color state management - global state needed for CLI output formatting
      - path: internal/cli/color\.go
        linters:
          - gochecknoglobals
        text: (colorEnabled|colorMu)

      # 4. Test helper mutex for serializing parallel tests
      - path: internal/cli/color_test\.go
        linters:
          - gochecknoglobals
        text: colorTestMutex
